name: lancebox
description: "LanceBox onboarding and invoicing case-study app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  file_picker: ^12.3.0
  pdf: ^3.12.0
  share_plus: ^13.3.0
  flutter_riverpod: ^3.3.2
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/Pretendard-Regular.ttf
    - assets/fonts/Pretendard-Bold.ttf
    - assets/fonts/Pretendard-LICENSE.txt
  fonts:
    - family: Pretendard Variable
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
